dist: trusty
os: linux

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      addons:
        apt:
          update: true
          sources:
            - google-chrome
          packages:
            - google-chrome-beta

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox