os: linux

language: node_js

node_js:
  - 12.0

dist: trusty

addons:
    chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

notifications:
  slack: argovis-testing:HEHQGPzyqGFuovtDGAqXrE8Q
  on_success: always # default: change
  on_failure: always # default: always