version: '3'
services:
  argo-express:
    image: argovis/argo-express:dev
    restart: always
    ports: 
    - '3000:3000'
    command: npm run devstart # development
    command: npm run start    # production
  database:
    image: mongo:4.2.3
    restart: always
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      # - /storage/mongodb:/data/db:Z # development
      - /data/argovis/storage/mongodb:/data/db:Z # production
  api:
    image: argovis/argovis_api:dev
    restart: always
    ports:
     - 8080:8080
  # netdata:
  #   image: netdata/netdata
  #   restart: always
  #   hostname: example.com # set to fqdn of host
  #   ports:
  #     - 19999:19999
  #   cap_add:
  #     - SYS_PTRACE
  #   security_opt:
  #     - apparmor:unconfined
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
